### PR TITLE
Decemeber tag 202112

### PR DESCRIPTION
**Pull request by rahulpatidar0191**
Modified the necessary python version in 
`docker-compose.generate_requirements.yml`
`.github/workflows/docker_image.yml`

Just to confirm we wont merge this branch into main, right?

### CODE REVIEW

**Review by hillairet — CHANGES_REQUESTED** [review]
Why did you downgrade to 3.9.6? I see 3.9.9 in [dockerhub](https://hub.docker.com/_/python/)
I also see 3.10.1 ...

Yes we will merge to main and create the tag/release on main once everything is ready for it.

**Comment by rahulpatidar0191** [comment]
@hillairet I downgraded to `3.9.6` as the last tag `4.2.1` uses  that version. I wasn't sure upgrading to 3.9.9 may break things. If that's not the case I can upgrade both 3.9 and 3.10 to newer versions. Let me know

**Comment by hillairet** [comment]
That point is now to upgrade everything to the latest.
The changes from 3.9.6 -> 3.9.9 will not break the APIs and the libraries, that's why they are patch version changes.

**Review by hillairet — CHANGES_REQUESTED** [review]
So that's just python version updates.
You need to update the packages too.
Please follow the instructions this way we know they are correct.

**Review by hillairet — CHANGES_REQUESTED** [review]
So that's just python version updates.
You need to update the packages too.
Please follow the instructions this way we know they are correct.

**Comment by rahulpatidar0191** [comment]
The packages are updated by running `docker-compose.generate_requirements.yml` right? I did it the first time but forgot while my second commit, it seems like they were identical this time so git isnt really showing them

**Comment by hillairet** [comment]
> I ran this one `docker-compose.generate_requirements.yml`

That's not a command, that's a file  :wink:

**Comment by rahulpatidar0191** [comment]
> > I ran this one `docker-compose.generate_requirements.yml`
> 
> That's not a command, that's a file 😉

True True. I ran this command 
`docker-compose -f docker-compose.generate_requirements.yml up`

**Comment by hillairet** [comment]
Ok since this is very confusing and in the interest of time, I committed my files.
I used the exact same command as you ...

**Comment by rahulpatidar0191** [comment]
> Ok since this is very confusing and in the interest of time, I committed my files. I used the exact same command as you ...

Thanks. I am getting tired of my windows machine. So many issue with the mounts I had to switch to my mac for this one

**Review by hillairet — APPROVED** [review]
Ready to go!  :+1:

**Pull request merged**
